### ISSUE TITLE
The sms_handler_demo not work on my huawei e303 modem, I have no response from the SMS that I send to the modem.

### ISSUE THREAD

**Issue by mariolicona** [faucamp/python-gsmmodem#41]

**Comment by Andati** [comment]
Add the following code after line 34 of sms_handler_demo.py:

``` python
modem.processStoredSms(unreadOnly=True)
```

So that the code reads:

``` python
try:    
    modem.processStoredSms(unreadOnly=True)
    modem.rxThread.join(2**31) # Specify a (huge) timeout so that it essentially blocks indefinitely, but still receives CTRL+C interrupt signal
finally:
```

**Comment by babca** [comment]
@mariolicona Make sure 
- you're using fixed pyserial module (older v2.7, or v3.1a0+ from git), v3.0.1 is broken
- you're using the correct serial port - there's no notifications on `/dev/ttyUSB0` port, you have to use `/dev/ttyUSB2` instead
- notifications are visible with serial console (`screen /dev/ttyUSB2 115200`, or `python tools/gsmterm.py -b 115200 /dev/ttyUSB2`), you should see messages like ^BOOT, ^RSSI, ^CSNR etc.

@Andati good tip for processing all older messages from the period the python daemon was not running, but it can't resolve the issue that mariolicona describes.

**Comment by andreisid** [comment]
hi, i have  the same issue as mariolicona. I downgraded pyserial to 2.7 but i can't use /dev/ttyUSB1 or 2. i'm getting the following when running sms_handler_demo:

serial_comms.py", line 135, in write
    raise TimeoutException()

**Comment by BaronBonet** [comment]
I'm also having this issue.

If I use `Port = '/dev/ttyUSB0'` I can read my number (using the `own_number_demo.py` example) and send messages (using the `modem.sendSms()` function).
However, I cannot seem to be able to access `/dev/ttyUSB2` so therefor I cannot receive messages.

- I am running Ubuntu 18.04 LTS
- I am using a Huawei K3765 modem
- I have changed permissions of `dev/ttyUSB2` with the command `chmod 777 /dev/ttyUSB2`
- If I run any of the demos with `PORT = '/dev/ttyUSB2'` when i'm not calling `sudo` I get the following error:
```
-> % python own_number_demo.py  
Initializing modem...
INFO: Connecting to modem on port /dev/ttyUSB2 at 115200bps
Traceback (most recent call last):
  File "/home/eric/.local/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
OSError: [Errno 16] Device or resource busy: '/dev/ttyUSB2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "own_number_demo.py", line 38, in <module>
    main()
  File "own_number_demo.py", line 22, in main
    modem.connect(PIN)
  File "/home/eric/.local/lib/python3.6/site-packages/gsmmodem/modem.py", line 199, in connect
    super(GsmModem, self).connect()
  File "/home/eric/.local/lib/python3.6/site-packages/gsmmodem/serial_comms.py", line 51, in connect
    timeout=self.timeout,*self.com_args,**self.com_kwargs)
  File "/home/eric/.local/lib/python3.6/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/eric/.local/lib/python3.6/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 16] could not open port /dev/ttyUSB2: [Errno 16] Device or resource busy: '/dev/ttyUSB2'
```
- if I run the demos and call `sudo` I get this error
```
-> % sudo python own_number_demo.py
Initializing modem...
INFO: Connecting to modem on port /dev/ttyUSB2 at 115200bps
DEBUG: write: ATZ
Traceback (most recent call last):
  File "own_number_demo.py", line 38, in <module>
    main()
  File "own_number_demo.py", line 22, in main
    modem.connect(PIN)
  File "/home/eric/.local/lib/python3.6/site-packages/gsmmodem/modem.py", line 211, in connect
    self.write('ATZ') # reset configuration
  File "/home/eric/.local/lib/python3.6/site-packages/gsmmodem/modem.py", line 459, in write
    responseLines = super(GsmModem, self).write(data + writeTerm, waitForResponse=waitForResponse, timeout=timeout, expectedResponseTermSeq=expectedResponseTermSeq)
  File "/home/eric/.local/lib/python3.6/site-packages/gsmmodem/serial_comms.py", line 144, in write
    raise TimeoutException()
gsmmodem.exceptions.TimeoutException: None
```

Any advice would be appreciated @babca. 

After some digging i think this might be a lower level problem and have posted a question on [superuser stackExchange](https://superuser.com/questions/1412935/linux-cu-command-returns-line-in-use)

**Comment by babca** [comment]
1. Please use a maintained fork:
https://github.com/babca/python-gsmmodem
faucamp's repo is abandoned.

2. Have you tried to use '/dev/ttyUSB1' port as well?

3. The device can be occupied by a another program or another instance of gsmmodem which is still running. Check running processes.

I was never forced to use `chmod` on /dev/ttyUSBx, defaults should be fine.

**Comment by BaronBonet** [comment]
Hi @babca, thanks a lot for your reply.  I am now using the maintained fork, and i just solved this issue.

I did try using `/dev/ttyUSB1` that also did not work

I solved the use by running `sudo lsof | grep tty`  from there i saw there was a process running on `/dev/ttyUSB2` once i killed that process `sudo kill <PID>` I was able to run the examples using `PORT = '/dev/ttyUSB2'` and now it is functioning as expected. 

The first time i didn't run `lsof` as the super user so i didn't see all the processes running. 

If you think it would be helpful I'll happily transfer this information to your fork.

**Comment by babca** [comment]
I couldn't remember the last time I saw this error. Now I remember, it was a process which occupied the port, as well. The same reason.

I created a simple FAQ section in https://github.com/babca/python-gsmmodem/blob/master/README.rst. Feel free to improve it 👍

**Comment by BaronBonet** [comment]
Looks great, thanks for maintaining this project and documenting. I'm
working on using this package in combination with Django to so i can upload
messages to a cloud server, which are then sent to a local computer (in
Lesotho) and then sent to local customers phones. The same also will work
in reverse (messages from phones -> to local computer -> to cloud server).
I'll try to document the process and once it's ready I'll share the project
with you in case your interested.

Thanks again!

**Comment by babca** [comment]
Great news Eric. Share it for everyone! :-)
