### ISSUE TITLE
get error while installing

### ISSUE THREAD

**Issue by ghorbanpirizad** [faucamp/python-gsmmodem#95]
I get this error when want install in both py2 , py3 why.
/data/user/0/org.qpython.qpy/files/bin/qpython3-android5.sh "/data/user/0/org.qpython.qpy/files/bin/pip4console3.py" && exit
les/bin/pip4console3.py" && exit         <
Input pip commands, ie: pip3 install {module}
-->pip3 install python-gsmmodem
Downloading/unpacking python-gsmmodem
  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (8  Downloading python-gsmmodem-0.9.tar.gz (87kB): 87kB downloaded
  Running setup.py egg_info for package python-gsmmodem
    Traceback (most recent call last):
      File "<string>", line 16, in <module>      File "/storage/emulated/0/qpython/cache/pip-build/python-gsmmodem/setup.py", line 25, in <module>
        class RunUnitTests(Command):
      File "/storage/emulated/0/qpython/cache/pip-build/python-gsmmodem/setup.py", line 29, in RunUnitTests
        description = __doc__[1:]
    TypeError: 'NoneType' object is not subscriptable
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/storage/emulated/0/qpython/cache/pip-build/python-gsmmodem/setup.py", line 25, in <module>

    class RunUnitTests(Command):

  File "/storage/emulated/0/qpython/cache/pip-build/python-gsmmodem/setup.py", line 29, in RunUnitTests

    description = __doc__[1:]

TypeError: 'NoneType' object is not subscriptable

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build/python-gsmmodem
Storing complete log in /sdcard/qpython/.pip/pip.log
-->

**Comment by tomchy** [comment]
Hi!
It seems that your problem is not related to the library itself, but to the python interpreter that you are using ( [similar issue](https://stackoverflow.com/questions/49822079/getting-docstring-in-qpython3) ).

Additionally you may consider moving to the python-gsmmodem-new package, which is recommended if you want to use it under python3 or with non-ascii characters.

**Comment by ghorbanpirizad** [comment]
I get same issue on python-gsmmodem-new. 
Is this for my py ver. That's 3.2 or because android?!

**Comment by tomchy** [comment]
I have a strong feeling that it is because you are using QPython. You may also modify manually the package and replace `__doc__` with a meaningful text, but this change will not be up-merged as the usage of `__doc__` is 100% valid in python.
